server:
  port: 8080

spring:
  datasource:
    druid:
      test-on-borrow: true
      test-while-idle: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(Q4cob5nVy0Trgz0YVcQ+Xg==)
    password: ENC(C5uJ4nXfiPFgimLBAs6ZL3LAMCy/0XqB)
    url: jdbc:mysql://103.243.26.140:3306/vpn?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

  redis:
    host: 103.243.26.140
    port: 6379 #port
    password: ENC(khqB555EvF31G24VnmexWQ==)
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

  mybatis-plus:
    global-config:
      db-config:
        id-type: auto
        field-strategy: not_empty
        table-underline: true
        db-type: mysql
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    mapper-locations: classpath:/com/dachui/vpn/mapper/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: -1
      max-request-size: -1
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false
  static-path-pattern: /static/**

minio:
  endpoint: http://103.243.26.140:9000 #Minio服务地址
  bucketName: vpn #桶
  accessKey: ENC(RCyQi4wvDM975k52j43dKTfaIXVDT2qQ)
  secretKey: ENC(RCyQi4wvDM975k52j43dKTfaIXVDT2qQ)

