server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://103.243.26.140:3306/vpn?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

  mybatis-plus:
    global-config:
      db-config:
        id-type: auto
        field-strategy: not_empty
        table-underline: true
        db-type: mysql
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    mapper-locations: classpath:/com/dachui/vpn/mapper/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 500MB
      max-request-size: 500MB
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false
  static-path-pattern: /static/**

minio:
  endpoint: http://localhost:9000 #Minio服务所在地址
  bucketName: tcc #存储桶名称
  accessKey: tanchuntcc #访问的key
  secretKey: tanchuntcc #访问的秘钥


redis:
  host: 103.243.26.140
  port: 6379 #port
  password:
  jedis:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0
  lettuce:
    shutdown-timeout: 0